# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: åŠ©åŠ›ç éšæœºä¸Šè½¦????

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,10,20 * *' # 12 o'clock in the evening on the 1st, 10th and 20th of each month
  watch:
    types: started
  repository_dispatch:
    types: jd_scripts
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“??? Action???
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ä½¿ç”¨ package-lock.json ??? Hash ä½œä¸ºç¼“å­˜??? keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      - name: npm install
        run: |
          npm install
      - name: 'è¿è¡Œ ã€åŠ©åŠ›ç éšæœºä¸Šè½¦ğŸš—???'
        run: |
          node shareBus.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
